title: Ray Cardoso
email: your-email@example.com
description: >- 
  Software Engineering.
baseurl: "" 
url: "" 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed